//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerPack.Common.Models
{    
    public class ListItem
    {
        public string ItemId { get; set; }
        public string ItemName { get; set; }
        public bool Selected { get; set; }
    }
}
